import 'dart:math';
import 'package:mobx/mobx.dart';
import 'package:mvvm/BOs/Whatsapp_View.dart'; // Assuming this contains the ContactInfo and Messages classes

// Required for MobX code generation
part 'WhatsAppScreenDetailModel.g.dart'; // This part will be generated by the build_runner

class WhatsAppScreenDetailModel = _WhatsAppScreenModelDetailBase with _$WhatsAppScreenDetailModel;

abstract class _WhatsAppScreenModelDetailBase with Store {
  
  // Observable list of messages
  @observable
  ObservableList<Messages> sendMessages = ObservableList<Messages>();

  // Observable list of possible replies
  @observable
  ObservableList<String> replayMessages = ObservableList.of([
    'Sure, I can help with that!',
    'Let me check on that.',
    'Sounds good!',
    'I’m not sure, can you clarify?',
    'That’s interesting!',
    'What do you think about it?',
    'Can you provide more details?',
    'Got it!',
  ]);

  // Action to send a message
  @action
  void sendMessage(String message) {
    if (message.isNotEmpty) {
      sendMessages.add(Messages(message, true)); // User message
      _sendRandomReply(); // Simulate system reply
    }
  }

  // Action to send a random reply after a delay
  @action
  Future<void> _sendRandomReply() async {
    await Future.delayed(Duration(seconds: 2)); // Delay before sending the reply
    String randomReply = _getRandomReply();
    sendMessages.add(Messages(randomReply, false)); // System reply
  }

  // Action to select a random reply
  @action
  String _getRandomReply() {
    final random = Random();
    int randomIndex = random.nextInt(replayMessages.length);
    return replayMessages[randomIndex];
  }
}
